site_name: Ingeniería de Software
site_description: Documentación del curso de Ingeniería de Software

nav:
  - Index : index.md
  - Semana 2 : 
     - Contenido : semana2/contenidosemana2.md
     - Tipos de datos y estructuras: semana2/tipos_datos.md
     - Control de flujo: semana2/control_flujo.md
  
  - Semana 3 : 
     - Introducción a Python: semana2/introduccion_python.md
     - Tipos de datos y estructuras: semana2/tipos_datos.md
     - Control de flujo: semana2/control_flujo.md
  
 
theme:
  name: 'material'
  language: 'es'
  font:
    text: Roboto
    code: Roboto Mono
  plugins: 
  #  - codeinclude 
   - search  

  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
    # - navigation.expand
    - navigation.sections  # Habilita la generación automática de índices
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    # - toc.integrate  # Habilita la integración de la tabla de contenido
    
    
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: purple
      accent: orange

extra_css:
  - assets/stylesheets/styles.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:pymdownx.emoji.gemoji
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid          
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@jborissalleg
#     - icon: simple/linkedin
#       link: https://linkedin.com/borissalleg
copyright: Copyright &copy; 2025 Boris Salleg
